DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS crew;
DROP TABLE IF EXISTS ship;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	privileges INTEGER NOT NULL,
	credits INTEGER NOT NULL,
	ship1 INTEGER,
	ship1job INTEGER,
	ship2 INTEGER,
	ship2job INTEGER,
	permcrew TEXT
);

CREATE TABLE crew (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL,
	species TEXT NOT NULL,
	level INTEGER NOT NULL,
	exp INTEGER NOT NULL,
	piloting INTEGER NOT NULL,
	melee INTEGER NOT NULL,
	diplomacy INTEGER NOT NULL,
	science INTEGER NOT NULL,
	alertness INTEGER NOT NULL,
	luck INTEGER NOT NULL,
	alive BOOLEAN NOT NULL
);

CREATE TABLE ship (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL,
	hull INTEGER NOT NULL,
	cargo INTEGER NOT NULL,
	engines INTEGER NOT NULL,
	weapons INTEGER NOT NULL,
	compute INTEGER NOT NULL,
	sensors INTEGER NOT NULL	
);

CREATE TABLE jobs (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE NOT NULL,
	type INTEGER NOT NULL,
	reward INTEGER NOT NULL,
	description TEXT UNIQUE NOT NULL,
	succeed TEXT UNIQUE NOT NULL,
	fail TEXT UNIQUE NOT NULL,
	level INTEGER NOT NULL
);